version: "0.2"
words:
  - ˈkweɪ
  - afdian
  - Boshen
  - Broooooklyn
  - Hiroshi
  - Ikuta
  - joshi
  - jsfiddle
  - jsrepo
  - Leproux
  - Lichter
  - Morote
  - naito
  - naitokosuke
  - NAPI
  - Natsuki
  - Nozomu
  - nuxt
  - nuxtjs
  - Ogawa
  - oxlint
  - Parsa
  - piña
  - Pooya
  - posva
  - Qing
  - Quarsar
  - Rspack
  - rstore
  - Sébastien
  - slidev
  - swrv
  - todde
  - Turborepo
  - unocss
  - unplugin
  - vuefes
  - vuejs
  - Vuetify
  - Xiangjun
  - Yogo
  - Yuichi
  - Yunfei
  - Zenn
